"""
RRR 8-27-15

This script creates a list of all the seqIDs in your .fasta file.
Then it creates a list of all the seqIDs in your .blast.table file.
Then it creates a new file of the missing seqIDs.
These seqIDs can later be concatenated to the below-cutoff seqID file
generated by the R script find_seqIDs_with_pident.R

The format for typing into the terminal is:

$ python fetch_seqIDs_blast_removed.py fastafile blastfile outputfile

where 	fetch_seqIDs_blast_removed.py		path to this script
		fastafile							path to the fasta file containing all the seqIDs
		blastfile							path to the blast results in table format (col1 = seqID)				
		outputfile							path to the file with \n delimited seqIDs the script creates

Acknowledgements: I would like to sincerely thank Dr. Josh Hamilton for his invaluable aid
in troubleshooting this script.
"""

# Import required libraries

import os	# a library for manipulating files on your computer
import sys	# a library for reading arguments from the command line


# Read input arguments from command line into variable names

fastafile = sys.argv[1]
blastfile = sys.argv[2]
outputfile = sys.argv[3]


# delete the output file if it already exists so that you append to a blank file

if os.path.isfile(outputfile) :
	os.remove(outputfile)
	print("Existing file with your chosen output file name was deleted.")


# Create List of all SeqIDs in fasta file

fasta = open(fastafile,"r")

LineType = 1	# when LineType=1 it is a >ID line, when LineType=-1 it is an ATGC line
allIDs = []

for line in fasta :
	if LineType == 1 :
		line = line.strip()
		allIDs.append(line[1:])
	LineType = LineType * -1


# Create List of all SeqIDs in blast output file

blast = open(blastfile,"r")

blastIDs = []

for line in blast :
	currentID = line.split()
	blastIDs.append(currentID[0])


# Find seqIDs that are missing in blast and append them to the missing IDs output file

for a in allIDs :
	counter = 0
	for b in blastIDs :
		if a == b :
			counter = 1
	if counter == 0 :
		with open(outputfile,"a") as missing :
			missing.write(a + "\n")


# Close all the files you've opened

fasta.close()
blast.close()
missing.close()

		

