---
title: "Database Improvement Workflow"
author: "Robin Rohwer"
date: "Last Updated 3/28/2018"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

These are steps that you can add to TaxAss in order to check for mistakes in your 
custom database.  Some of them are scripts that you run as part of TaxAss, and others 
are scripts that you use before TaxAss directly on the files that arb exports.

*the file names are not consistent yet*

# <span style="color:SteelBlue">Pre-processing</span>  

Follow these sections of `how_to_format_FreshTrain_ARB_export_for_TaxAss.html` to get the starting FreshTrain file:  

* ARB export  
* Simple Reformatting 
* Remove Non-FreshTrain References  
* Remove k\_\_, p\_\_, c\_\_, o\_\_ (if using SILVA)

Don't do the later steps of adjusting coarse-level nomenclature, this workflow here helps you figure 
out *how* to adjust the coarse-level nomenclature.

--------------------------------------------------------------------------------------------

# <span style="color:SteelBlue">Overview</span> 

These scripts are in the tax-scripts folder because they are also used in the TaxAss workflow. 
They require files generated in the workflow. Call these scripts from within your working 
directory and at the correct point in the workflow processing.)


* **Update coarse-level nomenclature**  
  `classify.seqs` (mothur)  
  `find_classification_disagreements.R`

* **Find typos that result in two fine-level taxa with the same name from having different coarse-level names.**  
	`find_typos.R`

* **Find abundant non-custom sequences**  
	`Find_Abund_SeqIDs_to_Add.R`

--------------------------------------------------------------------------------------------

# <span style="color:SteelBlue">Update coarse-level nomenclature</span>  

Identify coarse-level nomenclature disagreements by comparing custom and general database names.
This identifies drift in database curation as the databases are updated separately.  

### Classify custom database fastas with the general database   

Full Command (Type in Terminal):
```
mothur "#classify.seqs(fasta=custom.fasta, template=general.fasta, taxonomy=general.taxonomy, method=wang, probs=T, processors=2, cutoff=0)"
```

file names                      | description
--------------------------------|----------------------------------------------
`custom.fasta`					        | the fasta file of the small, custom database
`general.fasta`					        | the fasta file of the large, general database
`custom.general.wang.taxonomy`  | the taxonomy of your custom database assigned by the general database<br>this is the default name created by mothur
`custom.general.taxonomy`			  | the custom.general.wang.taxonomy file renamed

### Reformat files

Full 2 Commands (Type in Terminal):
```
sed 's/[[:blank:]]/\;/' <custom.general.wang.taxonomy >custom.general.taxonomy
sed 's/[[:blank:]]/\;/' <custom.taxonomy >custom.custom.taxonomy
```

This makes the files semicolon delimited for import into the next R script. File names are consistent with those used in the TaxAss directions.    

### Find Nomenclature disagreements 

```
mkdir conflicts_database
Rscript find_classification_disagreements.R custom.custom.taxonomy custom.general.taxonomy NA conflicts_database NA NA 70 database 
```

command argument                      | description
--------------------------------------|----------------------------------------------
`Rscript`									            | this opens R to accept arguments from the command line
`find_classification_disagreements.R`	|	this is the R script you're sourcing
`custom.custom.taxonomy`					    | this is the path to your custom taxonomy database after re-formatting it in step 12.
`custom.general.taxonomy`					    | this is the path to your custom taxonomy database classified using the general database in step 11.
`NA`										              | NA is typed as a placeholder here
`conflicts_database`						      | this is the path to the folder you want the R script to save the .csv results files in. You create this folder in this step with the mkdir command.
`NA`										              | NA is typed as a placeholder here
`NA`										              | NA is typed as a placeholder here
`70`										              | this is the p-value cutoff for the general database assignments of the custom database fastas. This determines if a classification is good enough to be named or should be "unclassified." 	
`database`								            | This flag tells the script you are comparing two databases instead of OTU classifications.

This generates a csv files that list nomenclature disagreements at each taxa-level. Note that it uses a bootstrap value and is stochastic- could consider running multiple times or lowering the bootstrap cutoff.

### <span style="color:Grey">Get an idea of baseline disagreement in databases</span>

<span style="color:Grey">Compare your two databases to get an idea of the baseline level of disagreement you can expect from their taxonomy classifications.  This was not super helpful so you can't do it from the command line anymore, you have to open up step 14's `plot_classification_disagreements.R` and uncomment out that part to do it manually.</span>
<br> <br>
<span style="color:Grey">The idea was that they could be a "baseline" for how much disagreement or forcing to expect as an artifact of the databases.  But I took it out because it was unhelpful. Basically, it didn't work because each OTU dataset has way fewer total OTUs than the databases, so there's always more database conflicts but that doesn't mean the conflict you saw was not a problem. But this might be worth playing with more. If you want to, just open the R script in RStudio, uncomment out the file path at the beginning and add the path to your database_conflicts folder from optional step 11.5. Then go to the very bottom section of the code, the "Use Functions" section, and uncomment out the plots you want to see. The functions they call will still be defined.</span>

___________________________________________________________________________________________

# <span style="color:SteelBlue">Find Typos</span>  

Find typos that result in two fine-level taxa with the same name from having different coarse-level names.  

```
Rscript find_typos.R custom.taxonomy-semicolon tax_typos
```

command argument                      | description
--------------------------------------|----------------------------------------------
`Rscript`									            | this opens R to accept arguments from the command line
`find_typos.R`                      	|	this is the R script you're sourcing
custom.taxonomy-semicolon             | semicolon-delimited custom taxonomy file  
tax_typos                             | folder to put results into  

___________________________________________________________________________________________

# <span style="color:SteelBlue">Find abundant unrepresented seqs</span>  

Find high-read seqIDs that are missing in the FW database- prioritize adding new references that represent them.


Use from within RStudio `Find_Abund_SeqIDs_to_Add.R`.




