# Take in the blast table generated by find_seqIDs_with_pident.R
# Analyze the blast hits, are the best hits being chosen first?

# purpose: are blast setting OK, or are they not returning full length hits that would make our cutoff.

