# RRR 8-2-16 ----

# Figure 2a and 2b: classification improvement

# this script starts with the summary files generated by step 15.a of the workflow.

# Fig 2a is also generated automatically by the workflow in step 15.a, but these are the paper- and poster-formatted versions.
# Fig 2a shows the classification improvement at each taxa level for Lake Mendota.

# Fig 2b is generated using the step 15.a output from running several datasets through the workflow.
# Fig 2b shows the classification improvement at a given taxa level in different freshwater ecosystems.



# ---- Define File Paths and other User Choices ----

mendota.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/ME_GG/analysis/plots/WorkflowImprovement-BesideData-Reads.csv"
mendota.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/ME_GG/analysis/plots/WorkflowImprovement-StackedData-Reads.csv"

michigan.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_mend_unclust/plots/WorkflowImprovement-BesideData-Reads.csv"
michigan.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_mend_unclust/plots/WorkflowImprovement-StackedData-Reads.csv"

danube.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/danube/plots/WorkflowImprovement-BesideData-Reads.csv"
danube.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/danube/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_bogs_epi/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_bogs_epi/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.hypo.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_bogs_hypo/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.hypo.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster/poster_bogs_hypo/plots/WorkflowImprovement-StackedData-Reads.csv"

mouse.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/mouse2/analysis/plots/WorkflowImprovement-BesideData-Reads.csv"
mouse.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/mouse2/analysis/plots/WorkflowImprovement-StackedData-Reads.csv"


file.paths.beside <- c(mendota.beside.file.path, michigan.beside.file.path, danube.beside.file.path, bogs.beside.file.path, bogs.hypo.beside.file.path, mouse.beside.file.path)
file.paths.stacked <- c(mendota.stacked.file.path, michigan.stacked.file.path, danube.stacked.file.path, bogs.stacked.file.path, bogs.hypo.stacked.file.path, mouse.stacked.file.path)

ecosystem.names <- c("mendota", "michigan", "danube", "bog.epi", "bog.hypo", "mouse")
taxa.names <- c("kingdom", "phylum", "class", "order", "lineage", "clade", "tribe")

# taxa.num <- 5   # 1 = kingdom, 2 = phylum, 3 = class, 4 = order, 5 = lineage, 6 = clade, 7 = tribe
# eco.num <- 1   # 1 = mendota, 2 = bogs.epi, 3 = bogs.hyp, 4 = danube, 5 = taihu, 6 = michigan

folder.path <- "~/Dropbox/PhD/Write It/draft 3/draft_3_figure_files/"

# ---- Define Functions to Import and Format ----

import.improvement.data <- function(FilePath){
  x.unformatted <- read.csv(file = FilePath, colClasses = "character", header = TRUE)
  x <- as.matrix(x.unformatted[ ,-1])
  x <- apply(X = x, MARGIN = 2, FUN = as.numeric)
  row.names(x) <- x.unformatted[ ,1]
  return(x)
}

make.empty.list.structure <- function(ListNames){
  empty.list <- list(NULL)
  for (e in 1:length(ListNames)){
    empty.list[[e]] <- 0
    names(empty.list)[e] <- ListNames[e]
  }
  return(empty.list)
}

fill.ecosystem.list <- function(FilesVector, EcoList){
  for (f in 1:length(FilesVector)){
    EcoList[[f]] <- import.improvement.data(FilePath = FilesVector[f])
  }
  return(EcoList)
}

reorganize.ecosystem.list.by.taxa.level <- function(EcoList, TaxaList){
  for(t in 1:length(TaxaList)){
    temp.table <- NULL
    for (e in 1:length(EcoList)){
      temp.table <- cbind(temp.table, EcoList[[e]][ ,t, drop = FALSE])
      colnames(temp.table)[e] <- names(EcoList)[e]
    }
    TaxaList[[t]] <- temp.table
  }
  return(TaxaList)
}


# ---- Define Functions to Plot Data ----

# This is modified from fancy.barplot() in plot_classification_improvement.R (workflow step 15).
fancy.barplot <- function(BesideData, StackedData, BarSpacing = c(0,1), YaxisMax = 100, PlotTitle = ""){
  y <- BesideData
  z <- StackedData
  bar.space.y <- BarSpacing
  bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change
  col.y <- "grey"
  col.z <- c("grey", "orange", "red")
 
  # find all values from the basic "beside" plot:
  num.sections <- ncol(y)
  bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
  tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
  empty.labels <- rep(x = "", times = num.sections)
  
  # calculate bar and label spacing
  bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
  bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
  loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]
  
  # make plots
  barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, main = PlotTitle)
  barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE, main = PlotTitle)           
  
  return(loc.labels)
}

# left over from inside of fancy.barplot 
# y.axis.label <- paste(DataType, "Classified (%)")
# beside.legend <- c("Left Bars- Greegenes", "Right Bars- Workflow")
# stacked.legend <- c("Unchanged", "Re-Classified","Newly-Classified")
# title.label <- "Classification Improvement"
# file.name <- paste(FolderPath, "/WorkflowImprovement-", DataType, "Classified.png", sep = "")
# 
# mtext(text = colnames(z), side = 1, line = 1, at = loc.labels)
# mtext(text = y.axis.label, side = 2, line = 2.2, cex = 1.5)
# mtext(text = beside.legend, side = 1, line = 3, col = col.y, at = c(1, 18), cex = 1.5, adj = c(0,1))
# mtext(text = stacked.legend, side = 3, line = c(0, -1.5, -3), at = 14, cex = 1.5, col = col.z, adj = 0)
# mtext(text = title.label, side = 3, line = 1.5, cex = 1.5, at = 3, adj = 0)
# unnecessary.message <- dev.off()


# ---- Use Functions to Import and Format ----

beside.eco.list <- make.empty.list.structure(ListNames = ecosystem.names)
stacked.eco.list <- make.empty.list.structure(ListNames = ecosystem.names)

beside.eco.list <- fill.ecosystem.list(FilesVector = file.paths.beside, EcoList = beside.eco.list)
stacked.eco.list <- fill.ecosystem.list(FilesVector = file.paths.stacked, EcoList = stacked.eco.list)

beside.tax.list <- make.empty.list.structure(ListNames = taxa.names)
stacked.tax.list <- make.empty.list.structure(ListNames = taxa.names)

beside.tax.list <- reorganize.ecosystem.list.by.taxa.level(EcoList = beside.eco.list, TaxaList = beside.tax.list)
stacked.tax.list <- reorganize.ecosystem.list.by.taxa.level(EcoList = stacked.eco.list, TaxaList = stacked.tax.list)

# ---- Use Functions to Plot all Combinations Quickly ----

# make a rough fig 2a for each ecosystem:
for (e in 1:length(ecosystem.names)){
  png(filename = paste(folder.path, "/fig_2a_", e, "-", ecosystem.names[e], ".png", sep = ""), width = 7, height = 5, units = "in", res = 100)
  label.loc <- fancy.barplot(BesideData = beside.eco.list[[e]], StackedData = stacked.eco.list[[e]], PlotTitle = ecosystem.names[e] )
  mtext(text = taxa.names, side = 1, line = 1, at = label.loc)
  dev.off()
}

# make a rough fig 2b for each taxa level:
for (t in 1:length(taxa.names)){
  png(filename = paste(folder.path, "/fig_2b_", t, "-", taxa.names[t], ".png", sep = ""), width = 7, height = 5, units = "in", res = 100)
  label.loc <- fancy.barplot(BesideData = beside.tax.list[[t]], StackedData = stacked.tax.list[[t]], PlotTitle = taxa.names[t])
  mtext(text = ecosystem.names, side = 1, line = 1, at = label.loc)
  dev.off()
}

# ---- Paper Figure ----

#note: requires eps formatting





# ---- Poster Figure ----

mendota.unclust.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_mend_unclust/plots/WorkflowImprovement-BesideData-Reads.csv"
mendota.unclust.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_mend_unclust/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.epi.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_epi/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.epi.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_epi/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.hypo.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_hypo/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.hypo.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_hypo/plots/WorkflowImprovement-StackedData-Reads.csv"

danube.10.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_danube_10/plots/WorkflowImprovement-BesideData-Reads.csv"
danube.10.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_danube_10/plots/WorkflowImprovement-StackedData-Reads.csv"

michigan.hiseq.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_michigan_hiseq/plots/WorkflowImprovement-BesideData-Reads.csv"
michigan.hiseq.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_michigan_hiseq/plots/WorkflowImprovement-StackedData-Reads.csv"

file.paths.beside <- c(mendota.unclust.beside.file.path, michigan.hiseq.beside.file.path, bogs.epi.beside.file.path, bogs.hypo.beside.file.path, danube.10.beside.file.path)
file.paths.stacked <- c(mendota.unclust.stacked.file.path, michigan.hiseq.stacked.file.path, bogs.epi.stacked.file.path, bogs.hypo.stacked.file.path, danube.10.stacked.file.path)

ecosystem.names <- c("eutrophic", "oligotrophic", "bog", "bog", "river")
taxa.names <- c("kingdom", "phylum", "class", "order", "family/", "genus/", "species/")
bar.labels.2 <- c("","","","lineage", "clade", "tribe", "", "lake", "lake", "epilimnion", "hypolimnion", "")

file.path <- "~/Dropbox/Trina/8-20-16_ISME16_figures/red_orange_improvement_plot.png"

# now source function definitions and calls.

clades.beside <- beside.tax.list$`family/`
clades.stacked <- stacked.tax.list$`family/`

mendota.beside <- beside.eco.list$eutrophic[ ,-1]
mendota.stacked <- stacked.eco.list$eutrophic[ ,-1]

all.beside <- cbind(mendota.beside, c(0,0), clades.beside)
all.stacked <- cbind(mendota.stacked, c(0,0,0),clades.stacked)

y <- all.beside
z <- all.stacked
YaxisMax = 100
bar.space.y <- c(0,1)
bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change
col.y <- "grey"
col.z <- c("grey", "orange", "red")
bar.labels <- c(taxa.names[-1], "", ecosystem.names)

# find all values from the basic "beside" plot:
num.sections <- ncol(y)
bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
empty.labels <- rep(x = "", times = num.sections)

# calculate bar and label spacing
bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]

y.lab <- seq(0, 100, 20)
y.label <- expression(bold("Percent Classified (Reads)"))
plot.1 <- expression(bold("Lake Mendota"))
plot.2 <- expression(bold("Genus/Clade"))
slider <-c(0,0,0,1,1,1,0,1,1,1,1,0)

legend.1 <- c(expression(bold("Left Bars: GreenGenes")), expression(bold("Right Bars: TaxAss")))
legend.2 <- c(expression(bold("Newly-Classified")), expression(bold("Re-Classified")), expression(bold("Unchanged")))

png(filename = file.path, width = 16.21, height = 5.96, units = "in", res = 300)
par(mar = c(6,.8,2.5,0))
barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
rect(xleft = loc.labels[7] - bar.width, ybottom = -10, xright = loc.labels[7] + bar.width, ytop = 10, border = NA, col = "white", xpd = T)

text(x = loc.labels - .5 * slider, y = -5, labels = bar.labels, srt = 40, xpd = T, cex = 1.5, adj = 1)
text(x = loc.labels + .5 * slider, y = -5, labels = bar.labels.2, srt = 40, xpd = T, cex = 1.5, adj = 1)

axis(side = 2, at = y.lab, labels = F, xpd = T, line = -4, lwd = 3, tick = T, lwd.ticks = 2)
mtext(text = y.lab, side = 2, at = y.lab, line = -3.5, cex = 1.5)

mtext(text = y.label, side = 2, line = -1, cex = 2)

axis(side = 2, at = y.lab, labels = F, xpd = T, line = -46, lwd = 3, tick = T, lwd.ticks = 2)
mtext(text = y.lab, side = 2, at = y.lab, line = -45.5, cex = 1.5)

mtext(text = plot.1, side = 3, line = 1, at = 4, adj = 0, cex = 2)
mtext(text = plot.2, side = 3, line = 1, at = 23, adj = 0, cex = 2)

mtext(text = legend.1, side = 3, line = c(2,0), at = 11, adj = 0, padj = 1, cex = 2, col = "grey")
mtext(text = legend.2, side = 3, line = c(2,0,-2), at = 36, adj = 1, padj = 1, cex = 2, col = c("red","orange","grey"))

dev.off()


