# RRR 8-2-16 ----

# Figure 2a and 2b: classification improvement

# this script starts with the summary files generated by step 15.a of the workflow.

# Fig 2a is also generated automatically by the workflow in step 15.a, but these are the paper- and poster-formatted versions.
# Fig 2a shows the classification improvement at each taxa level for Lake Mendota.

# Fig 2b is generated using the step 15.a output from running several datasets through the workflow.
# Fig 2b shows the classification improvement at a given taxa level in different freshwater ecosystems.



# ---- Define File Paths and other User Choices ----

mendota.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Mendota/TaxAss-Mendota/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
mendota.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Mendota/TaxAss-Mendota/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"

michigan.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Michigan/TaxAss-Michigan/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
michigan.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Michigan/TaxAss-Michigan/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"

danube.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Danube/TaxAss-Danube/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
danube.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/Danube/TaxAss-Danube/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"

bogs.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/TroutBogEpi/TaxAss-TroutBogEpi/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
bogs.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/TroutBogEpi/TaxAss-TroutBogEpi/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"

bogs.hypo.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/TroutBogHypo/TaxAss-TroutBogHypo/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
bogs.hypo.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/TroutBogHypo/TaxAss-TroutBogHypo/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"

mouse.beside.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/MouseGut/TaxAss-MouseGut/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-BesideData-Reads.csv"
mouse.stacked.file.path <- "~/Desktop/2018-05-10_taxass_server_results_for_resubmission/MouseGut/TaxAss-MouseGut/plots/step_15_5a_Improvement_over_general-only/WorkflowImprovement-StackedData-Reads.csv"


file.paths.beside <- c(mendota.beside.file.path, michigan.beside.file.path, danube.beside.file.path, bogs.beside.file.path, bogs.hypo.beside.file.path, mouse.beside.file.path)
file.paths.stacked <- c(mendota.stacked.file.path, michigan.stacked.file.path, danube.stacked.file.path, bogs.stacked.file.path, bogs.hypo.stacked.file.path, mouse.stacked.file.path)

ecosystem.names <- c("Mendota", "Michigan", "Danube", "Bog Epilimnion", "Bog Hypolimnion", "Mouse Gut")
taxa.names <- c("Kingdom", "Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# taxa.num <- 5   # 1 = kingdom, 2 = phylum, 3 = class, 4 = order, 5 = lineage, 6 = clade, 7 = tribe
# eco.num <- 1   # 1 = mendota, 2 = bogs.epi, 3 = bogs.hyp, 4 = danube, 5 = taihu, 6 = michigan

folder.path <- "~/Desktop/" # for quick looks export

# ---- Define Functions to Import and Format ----

import.improvement.data <- function(FilePath){
  x.unformatted <- read.csv(file = FilePath, colClasses = "character", header = TRUE)
  x <- as.matrix(x.unformatted[ ,-1])
  x <- apply(X = x, MARGIN = 2, FUN = as.numeric)
  row.names(x) <- x.unformatted[ ,1]
  return(x)
}

make.empty.list.structure <- function(ListNames){
  empty.list <- list(NULL)
  for (e in 1:length(ListNames)){
    empty.list[[e]] <- 0
    names(empty.list)[e] <- ListNames[e]
  }
  return(empty.list)
}

fill.ecosystem.list <- function(FilesVector, EcoList){
  for (f in 1:length(FilesVector)){
    EcoList[[f]] <- import.improvement.data(FilePath = FilesVector[f])
  }
  return(EcoList)
}

reorganize.ecosystem.list.by.taxa.level <- function(EcoList, TaxaList){
  for(t in 1:length(TaxaList)){
    temp.table <- NULL
    for (e in 1:length(EcoList)){
      temp.table <- cbind(temp.table, EcoList[[e]][ ,t, drop = FALSE])
      colnames(temp.table)[e] <- names(EcoList)[e]
    }
    TaxaList[[t]] <- temp.table
  }
  return(TaxaList)
}


# ---- Define Functions to Plot Data ----

# This is modified from fancy.barplot() in plot_classification_improvement.R (workflow step 15).
fancy.barplot <- function(BesideData, StackedData, BarSpacing = c(0,1), YaxisMax = 100, PlotTitle = ""){
  y <- BesideData
  z <- StackedData
  bar.space.y <- BarSpacing
  bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change
  col.y <- "grey"
  col.z <- c("grey", "orange", "red")
 
  # find all values from the basic "beside" plot:
  num.sections <- ncol(y)
  bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
  tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
  empty.labels <- rep(x = "", times = num.sections)
  
  # calculate bar and label spacing
  bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
  bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
  loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]
  
  # make plots
  barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, main = PlotTitle)
  barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE, main = PlotTitle)           
  
  return(loc.labels)
}

# ---- Use Functions to Import and Format ----

beside.eco.list <- make.empty.list.structure(ListNames = ecosystem.names)
stacked.eco.list <- make.empty.list.structure(ListNames = ecosystem.names)

beside.eco.list <- fill.ecosystem.list(FilesVector = file.paths.beside, EcoList = beside.eco.list)
stacked.eco.list <- fill.ecosystem.list(FilesVector = file.paths.stacked, EcoList = stacked.eco.list)

beside.tax.list <- make.empty.list.structure(ListNames = taxa.names)
stacked.tax.list <- make.empty.list.structure(ListNames = taxa.names)

beside.tax.list <- reorganize.ecosystem.list.by.taxa.level(EcoList = beside.eco.list, TaxaList = beside.tax.list)
stacked.tax.list <- reorganize.ecosystem.list.by.taxa.level(EcoList = stacked.eco.list, TaxaList = stacked.tax.list)

# ---- Use Functions for Quick Look at All Combinations ----

# make a rough fig 2a for each ecosystem:
for (e in 1:length(ecosystem.names)){
  # png(filename = paste(folder.path, "/fig_2a_", e, "-", ecosystem.names[e], ".png", sep = ""), width = 7, height = 5, units = "in", res = 100)
  label.loc <- fancy.barplot(BesideData = beside.eco.list[[e]], StackedData = stacked.eco.list[[e]], PlotTitle = ecosystem.names[e] )
  mtext(text = taxa.names, side = 1, line = 1, at = label.loc)
  # dev.off()
}

# make a rough fig 2b for each taxa level:
for (t in 1:length(taxa.names)){
  # png(filename = paste(folder.path, "/fig_2b_", t, "-", taxa.names[t], ".png", sep = ""), width = 7, height = 5, units = "in", res = 100)
  label.loc <- fancy.barplot(BesideData = beside.tax.list[[t]], StackedData = stacked.tax.list[[t]], PlotTitle = taxa.names[t])
  mtext(text = ecosystem.names, side = 1, line = 1, at = label.loc)
  # dev.off()
}

# ---- Paper Figure 2----

# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/red_yellow_improvement.pdf"

# setEPS()
# postscript(file = save.to, width = 6.875, height = 3, title = "TaxAss Fig 2", colormodel = "srgb", family = "Helvetica")

pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Fig 2", colormodel = "srgb")

par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right

# 2a.
y <- beside.eco.list$Mendota
z <- stacked.eco.list$Mendota
y <- y[ ,-1]
z <- z[ ,-1]

plot.title <- "Mendota by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# guts of generating plot (same for both panels) ------------------------------------------------
y.axis.label <- "Reads Classified (%)"
y.ticks <- c(0,20,40,60,80,100)
col.y <- "grey"
col.z <- c("grey", "orange", "red")

YaxisMax = 100
bar.space.y <- c(0,1)
bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change

# find all values from the basic "beside" plot:
num.sections <- ncol(y)
bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
empty.labels <- rep(x = "", times = num.sections)

# calculate bar and label spacing
bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]

# adjustments of labels etc (same for both panels)
barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)           
# Y axis
axis(side = 2, at = y.ticks, labels = FALSE, line = -1, tck = -.03)
mtext(text = y.ticks, at = y.ticks, side = 2, line = -.5, cex = .8, las = 1)
# X axis
text(x = loc.labels - .5, y = -4, labels = x.axis.labels, srt = -30, xpd = NA, cex = .8, adj = 0)
# Title
mtext(text = plot.title, side = 3, line = .7, cex = 1, at = 1, adj = 0)
# ----------------------------------------------------------------------------------------------------

# Y label
mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)

# 2b. 
y <- beside.tax.list$`Genus/Clade`
z <- stacked.tax.list$`Genus/Clade`

plot.title <- "Genus/Clade by Ecosystem"
x.axis.labels <- colnames(z)

# don't change this section, change above then copy to here ------------------------------------------------
y.axis.label <- "Reads Classified (%)"
y.ticks <- c(0,20,40,60,80,100)
col.y <- "grey"
col.z <- c("grey", "orange", "red")

YaxisMax = 100
bar.space.y <- c(0,1)
bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change

# find all values from the basic "beside" plot:
num.sections <- ncol(y)
bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
empty.labels <- rep(x = "", times = num.sections)

# calculate bar and label spacing
bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]

# adjustments of labels etc (same for both panels)
barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)           
# Y axis
axis(side = 2, at = y.ticks, labels = FALSE, line = -1, tck = -.03)
mtext(text = y.ticks, at = y.ticks, side = 2, line = -.5, cex = .8, las = 1)
# X axis
text(x = loc.labels - .5, y = -4, labels = x.axis.labels, srt = -30, xpd = NA, cex = .8, adj = 0)
# Title
mtext(text = plot.title, side = 3, line = .7, cex = 1, at = 1, adj = 0)
# ----------------------------------------------------------------------------------------------------

# legend beside 
beside.legend <- c("Left Bar: Greegenes", "Right Bar: TaxAss")
text(x = 16.8, y = c(102, 92), labels = beside.legend, adj = 0, xpd = NA, cex = .8)
rect(xleft = 15.5, xright = 16.5, ybottom = 100, ytop = 105, col = col.z[1], xpd = NA)
rect(xleft = 15.5, xright = 16.5, ybottom = 90, ytop = 91.7, col = col.z[1], xpd = NA)
rect(xleft = 15.5, xright = 16.5, ybottom = 91.6, ytop = 93.3, col = col.z[2], xpd = NA)
rect(xleft = 15.5, xright = 16.5, ybottom = 93.2, ytop = 95, col = col.z[3], xpd = NA)

# legend stacked 
stacked.legend <- c("Newly-Classified", "Re-Classified", "Unchanged")
text(x = 16.8, y = c(77,67,57), labels = stacked.legend, adj = 0, xpd = NA, cex = .8)
rect(xleft = 15.5, xright = 16.5, ybottom = 75, ytop = 80, col = col.z[3])
rect(xleft = 15.5, xright = 16.5, ybottom = 65, ytop = 70, col = col.z[2])
rect(xleft = 15.5, xright = 16.5, ybottom = 55, ytop = 60, col = col.z[1])

dev.off()

#
# ---- Paper Figure 2 supplemental ----
# same fig with other datasets. split into 1 panel each. easiest way, just crop off an empty plot.new at end.

# Mendota ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Mendota.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$Mendota
z <- stacked.eco.list$Mendota
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Mendota by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Michigan ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Michigan.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$Michigan
z <- stacked.eco.list$Michigan
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Michigan by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Danube ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Danube.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$Danube
z <- stacked.eco.list$Danube
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Danube by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Bog Epi ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_BogEpi.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$`Bog Epilimnion`
z <- stacked.eco.list$`Bog Epilimnion`
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Bog Epilimnion by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()


# Bog Hypo ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_BogHypo.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$`Bog Hypolimnion`
z <- stacked.eco.list$`Bog Hypolimnion`
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Bog Hypolimnion by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Mouse Gut ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_MouseGut.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2a.
y <- beside.eco.list$`Mouse Gut`
z <- stacked.eco.list$`Mouse Gut`
y <- y[ ,-1]
z <- z[ ,-1]
plot.title <- "Mouse Gut by Taxa Level"
x.axis.labels <- c("Phylum", "Class", "Order", "Family/Lineage", "Genus/Clade", "Species/Tribe")

# ***** RUN "GUTS" section *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Phylum ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Phylum.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$Phylum
z <- stacked.tax.list$Phylum
plot.title <- "Phylum by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()


# Class ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Class.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$Class
z <- stacked.tax.list$Class
plot.title <- "Class by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()


# Order ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Order.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$Order
z <- stacked.tax.list$Order
plot.title <- "Order by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()


# Family/Lineage ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Lineage.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$`Family/Lineage`
z <- stacked.tax.list$`Family/Lineage`
plot.title <- "Family/Lineage by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Genus/Clade ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Clade.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$`Genus/Clade`
z <- stacked.tax.list$`Genus/Clade`
plot.title <- "Genus/Clade by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()

# Species/Tribe ----
# save.to <- "~/Dropbox/PhD/Write It/draft 7/re-submission_figures/Supplemental_red-yellow_Tribe.pdf"
pdf(file = save.to, width = 6.875, height = 3, family = "Helvetica", title = "TaxAss Supplemental Fig 2", colormodel = "srgb")
par(mfrow = c(1,2), mai = c(.65, .05, .33, 0), omi = c(0, .36, 0, .9)) # bottom, left, top, right
# 2b. 
y <- beside.tax.list$`Species/Tribe`
z <- stacked.tax.list$`Species/Tribe`
plot.title <- "Species/Tribe by Ecosystem"
x.axis.labels <- colnames(z)

# ***** RUN "GUTS" section, line 181 *****

mtext(text = y.axis.label, side = 2, line = 1, cex = 1.1)
# empty side:
plot.new()
dev.off()


#
# ---- Poster Figure ----

mendota.unclust.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_mend_unclust/plots/WorkflowImprovement-BesideData-Reads.csv"
mendota.unclust.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_mend_unclust/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.epi.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_epi/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.epi.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_epi/plots/WorkflowImprovement-StackedData-Reads.csv"

bogs.hypo.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_hypo/plots/WorkflowImprovement-BesideData-Reads.csv"
bogs.hypo.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_bogs_hypo/plots/WorkflowImprovement-StackedData-Reads.csv"

danube.10.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_danube_10/plots/WorkflowImprovement-BesideData-Reads.csv"
danube.10.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_danube_10/plots/WorkflowImprovement-StackedData-Reads.csv"

michigan.hiseq.beside.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_michigan_hiseq/plots/WorkflowImprovement-BesideData-Reads.csv"
michigan.hiseq.stacked.file.path <- "~/Desktop/TaxonomyTrainingSets/BLASTing/poster_michigan_hiseq/plots/WorkflowImprovement-StackedData-Reads.csv"

file.paths.beside <- c(mendota.unclust.beside.file.path, michigan.hiseq.beside.file.path, bogs.epi.beside.file.path, bogs.hypo.beside.file.path, danube.10.beside.file.path)
file.paths.stacked <- c(mendota.unclust.stacked.file.path, michigan.hiseq.stacked.file.path, bogs.epi.stacked.file.path, bogs.hypo.stacked.file.path, danube.10.stacked.file.path)

ecosystem.names <- c("eutrophic", "oligotrophic", "bog", "bog", "river")
taxa.names <- c("kingdom", "phylum", "class", "order", "family/", "genus/", "species/")
bar.labels.2 <- c("","","","lineage", "clade", "tribe", "", "lake", "lake", "epilimnion", "hypolimnion", "")

file.path <- "~/Dropbox/Trina/8-20-16_ISME16_figures/red_orange_improvement_plot.png"

# now source function definitions and calls.

clades.beside <- beside.tax.list$`family/`
clades.stacked <- stacked.tax.list$`family/`

mendota.beside <- beside.eco.list$eutrophic[ ,-1]
mendota.stacked <- stacked.eco.list$eutrophic[ ,-1]

all.beside <- cbind(mendota.beside, c(0,0), clades.beside)
all.stacked <- cbind(mendota.stacked, c(0,0,0),clades.stacked)

y <- all.beside
z <- all.stacked
YaxisMax = 100
bar.space.y <- c(0,1)
bar.width <- 1  # spacing and axis limits will determine what width 1 looks like, no need to change
col.y <- "grey"
col.z <- c("grey", "orange", "red")
bar.labels <- c(taxa.names[-1], "", ecosystem.names)

# find all values from the basic "beside" plot:
num.sections <- ncol(y)
bar.spots <- barplot(y, beside = TRUE, width = bar.width, space = bar.space.y, plot = FALSE)
tot.x <- max(bar.spots) + .5 * bar.width + bar.space.y[2]
empty.labels <- rep(x = "", times = num.sections)

# calculate bar and label spacing
bar.space.beside <- c(bar.space.y[2], rep(bar.space.y[1] + bar.space.y[2] + bar.width, length.out = num.sections - 1))
bar.space.stacked <- bar.space.y[2] + bar.width + bar.space.y[1]
loc.labels <- bar.spots[seq(from = 1, to = length(bar.spots), by = 2)] + .5 * bar.width + .5 * bar.space.y[1]

y.lab <- seq(0, 100, 20)
y.label <- expression(bold("Percent Classified (Reads)"))
plot.1 <- expression(bold("Lake Mendota"))
plot.2 <- expression(bold("Genus/Clade"))
slider <-c(0,0,0,1,1,1,0,1,1,1,1,0)

legend.1 <- c(expression(bold("Left Bars: GreenGenes")), expression(bold("Right Bars: TaxAss")))
legend.2 <- c(expression(bold("Newly-Classified")), expression(bold("Re-Classified")), expression(bold("Unchanged")))

png(filename = file.path, width = 16.21, height = 5.96, units = "in", res = 300)
par(mar = c(6,.8,2.5,0))
barplot(y[1, ], col = col.y, border = "black", beside = FALSE, width = bar.width, space = bar.space.beside, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
barplot(z, add = TRUE, col = col.z, border = "black", beside = FALSE, width = bar.width, space = bar.space.stacked, xlim = c(0, tot.x), ylim = c(0, YaxisMax), names.arg = empty.labels, axes = FALSE)
rect(xleft = loc.labels[7] - bar.width, ybottom = -10, xright = loc.labels[7] + bar.width, ytop = 10, border = NA, col = "white", xpd = T)

text(x = loc.labels - .5 * slider, y = -5, labels = bar.labels, srt = 40, xpd = T, cex = 1.5, adj = 1)
text(x = loc.labels + .5 * slider, y = -5, labels = bar.labels.2, srt = 40, xpd = T, cex = 1.5, adj = 1)

axis(side = 2, at = y.lab, labels = F, xpd = T, line = -4, lwd = 3, tick = T, lwd.ticks = 2)
mtext(text = y.lab, side = 2, at = y.lab, line = -3.5, cex = 1.5)

mtext(text = y.label, side = 2, line = -1, cex = 2)

axis(side = 2, at = y.lab, labels = F, xpd = T, line = -46, lwd = 3, tick = T, lwd.ticks = 2)
mtext(text = y.lab, side = 2, at = y.lab, line = -45.5, cex = 1.5)

mtext(text = plot.1, side = 3, line = 1, at = 4, adj = 0, cex = 2)
mtext(text = plot.2, side = 3, line = 1, at = 23, adj = 0, cex = 2)

mtext(text = legend.1, side = 3, line = c(2,0), at = 11, adj = 0, padj = 1, cex = 2, col = "grey")
mtext(text = legend.2, side = 3, line = c(2,0,-2), at = 36, adj = 1, padj = 1, cex = 2, col = c("red","orange","grey"))

dev.off()

# end ----
